# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Validate YAML Files
on:
  pull_request:
  push:
    paths:
      - 'data'
    
jobs:
  validate-deadlines:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
    
      - name: Validate Deadlines
        uses: thiagodnf/yaml-schema-checker@main
        with:
          jsonSchemaFile: schemas/deadlines.schema.json
          yamlFiles: data/deadlines/events/**/*.yml
